[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ModDotPlot"
version = "1.0.0"
requires-python = ">=3.11,<3.15"
dependencies = [
  "pandas",
  "matplotlib>=3.11.2",
  "plotly",
  "dash",
  "plotnine>=0.15.8,<0.16",
  "palettable",
  "setproctitle",
  "numpy",
  "scipy",
  "pillow",
  "cooler",
]
authors = [
  {name = "Alex Sweeten", email = "alex.sweeten@nih.gov"},
  {name = "Michael Schatz"},
  {name = "Adam Phillippy"},
]
maintainers = [
  {name = "Alex Sweeten", email = "alex.sweeten@nih.gov"}
]
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
keywords = ["dotplot", "sketching", "modimizer", "heatmap"]

[project.scripts]
moddotplot = "moddotplot.__main__:main"

[project.optional-dependencies]
# development dependency groups
test = [
    "pytest",
    "pytest-cov",
]
